FROM debian:10.4-slim AS toolchain_builder
# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive
# Install required dependencies
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils \
    && apt-get install -y \
    wget \
    bzip2 \
    gcc \
    g++ \
    make \
    file \
    libmpfr-dev \
    libmpc-dev \
    zlib1g-dev \
    texinfo \
    git \
    gcc-multilib
